name: CMake Build

on: 
  push:
    paths-ignore: 
        - '**/picture/**'
        - 'packaging/**'
        - '.clang-*'
        - '.gitignore'
        - 'LICENSE'
        - '*.pro'
        - 'README*'
  pull_request:
    paths-ignore: 
        - '**/picture/**'
        - 'packaging/**'
        - '.clang-*'
        - '.gitignore'
        - 'LICENSE'
        - '*.pro'
        - 'README*'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        build_type:
          - "RelWithDebInfo"
        generators:
          - "Ninja"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ./.github/actions/install-dependencies
        with:
          os_name: ${{ matrix.os }}

      - name: Configure and build windows
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: |
          .\scripts\windows\setVsDev.ps1
          cmake `
            -S . `
            -B ./build `
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
            -G "${{ matrix.generators }}"
          cmake --build ./build --config ${{ matrix.build_type }}
      - name: Configure and build on ubuntu or macos
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        shell: bash
        run: |
          cmake \
            -S . \
            -B ./build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -G "${{ matrix.generators }}"
          cmake --build ./build --config ${{ matrix.build_type }}
