name: CMake Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'packaging/**'
      - 'qmake/**'
      - 'translations/**'
      - '**/*.md'
      - '**/*.txt'
      - '**/.clang-*'
      - '**/.gitignore'
      - '**/*.pri'
      - '**/LICENSE*'
      - '**/*.pro'
      - '**/README*'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'packaging/**'
      - 'qmake/**'
      - 'translations/**'
      - '**/*.md'
      - '**/*.txt'
      - '**/.clang-*'
      - '**/.gitignore'
      - '**/*.pri'
      - '**/LICENSE*'
      - '**/*.pro'
      - '**/README*'

env:
  MACOSX_DEPLOYMENT_TARGET: '13.0'
  MACOSX_BUILD_ARCHS: 'x86_64;arm64'
  BUILD_DIR: build
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        generators:
          - "Ninja"

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - uses: ./.github/actions/install-dependencies

      - name: Configure and build windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          .\packaging\windows\Enter-VsDevShell.ps1
          cmake `
            -S . `
            -B "${{ env.BUILD_DIR }}" `
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} `
            -G "${{ matrix.generators }}"
          cmake --build "${{ env.BUILD_DIR }}" --config ${{ env.BUILD_TYPE }}

      - name: Configure and build ubuntu
        if: runner.os == 'Linux'
        shell: bash
        run: |
          cmake \
            -S . \
            -B "${{ env.BUILD_DIR }}" \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -G "${{ matrix.generators }}"
          cmake --build "${{ env.BUILD_DIR }}" --config ${{ env.BUILD_TYPE }}

      - name: Configure and build macos
        if: runner.os == 'macOS'
        shell: bash
        run: |
          cmake \
            -S . \
            -B "${{ env.BUILD_DIR }}" \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DCMAKE_OSX_ARCHITECTURES="${{ env.MACOSX_BUILD_ARCHS }}" \
            -G "${{ matrix.generators }}"
          cmake --build "${{ env.BUILD_DIR }}" --config ${{ env.BUILD_TYPE }}
