name: Build MacOS

on: 
  push:
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
        - 'LICENSE'
        - '.gitignore'
        - 'README.md'
        - 'Scripts/**'
  pull_request:
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
        - 'LICENSE'
        - '.gitignore'
        - 'README.md'
        - 'Scripts/**'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0]
        qt_ver: [6.2.2]
        qt_arch: [clang_64]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          install-deps: 'true'
          modules: 'addons.qtcharts addons.qtnetworkauth'
          cached: 'false'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build macos
        run: |
          qmake
          make
