name: QMake Build

on: 
  push:
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
        - '**/picture/**'
        - 'cmake/**'
        - 'packaging/**'
        - '.clang-*'
        - '.gitignore'
        - 'CMake*'
        - 'LICENSE'
        - 'README*'
  pull_request:
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
        - '**/picture/**'
        - 'cmake/**'
        - 'packaging/**'
        - '.clang-*'
        - '.gitignore'
        - 'CMake*'
        - 'LICENSE'
        - 'README*'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 1
          
      - uses: ./.github/actions/install-dependencies
        with:
          os_name: ${{ matrix.os }}

      - uses: RealChuan/install-jom@main

      - name: mkdir build
        shell: bash
        run: |
          mkdir build

      - name: msvc-build
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: |
          ..\scripts\windows\setVsDev.ps1
          & qmake ./../.
          & jom
        working-directory: build
      - name: ubuntu-build
        if: startsWith(matrix.os, 'ubuntu')
        shell: bash
        run: |
          qmake ./../.
          make -j $(nproc)
        working-directory: build
      - name: macos-build
        if: startsWith(matrix.os, 'macos')
        shell: bash
        run: |
          qmake ./../.
          make -j $(sysctl -n hw.ncpu)
        working-directory: build