name: QMake Build

on: 
  push:
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
        - 'picture'
        - '.clang-format'
        - '.gitignore'
        - 'LICENSE'
        - 'README*'
        - 'Scripts'
  pull_request:
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
        - 'picture'
        - '.clang-format'
        - '.gitignore'
        - 'LICENSE'
        - 'README*'
        - 'Scripts'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - macos-latest
          - ubuntu-latest
        qt_ver: 
          - 6.5.0

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          install-deps: 'true'
          modules: 'addons.qtcharts addons.qtnetworkauth'
          cache: 'true'
      - name: ubuntu install GL library
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install -y build-essential libgl1-mesa-dev
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: msvc-build
        if: startsWith(matrix.os, 'windows')
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          qmake
          nmake
      - name: build macos or ubuntu
        if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
        run: |
          qmake
          make -j4
